//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TıklaKap
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMIN
    {
        public byte ID { get; set; }
        public string Kadi { get; set; }
        public string Sifre { get; set; }
    }
}
